version: '3.7'

services:
  db:
    image: postgres:16
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: parking_app_db